direnv: Add `layout uv`

diff --git a/home-manager/direnvrc b/home-manager/direnvrc
--- a/home-manager/direnvrc
+++ b/home-manager/direnvrc
@@ -6,15 +6,33 @@ layout_poetry() {
     exit 2
   fi
 
-  local VENV;
+  local VENV
   VENV=$(poetry env info --path)
   if [[ -z $VENV || ! -d $VENV/bin ]]; then
-    # We don't want to fail with error here, as it will break the direnv load
     log_error 'No poetry virtual environment found. Use `poetry install` to create one first.'
     return
   fi
 
   export VIRTUAL_ENV=$VENV
   export POETRY_ACTIVE=1
+  PATH_add "$VENV/bin"
+}
+
+layout_uv() {
+  if [[ ! -f pyproject.toml ]]; then
+    log_error 'No pyproject.toml found. Use `uv init` to create one first.'
+    exit 2
+  fi
+
+  local VENV;
+  VENV=".venv"
+  if [[ ! -d $VENV/bin ]]; then
+    # We don't want to fail with error here, as it will break the direnv load
+    log_error 'No uv virtual environment found. Use `uv sync` to create one first.'
+    return
+  fi
+
+  export VIRTUAL_ENV=$(expand_path "$VENV")
+  export PYTHONNOUSERSITE=true
   PATH_add "$VENV/bin"
 }
